champ_role = {
    "Aatrox": "Top",
    "Ahri": "Mid",
    "Akali": "Mid",
    "Akshan": "Mid",
    "Alistar": "Support",
    "Amumu": "Jungler",
    "Anivia": "Mid",
    "Annie": "Mid",
    "Aphelios": "AD Carry",
    "Ashe": "AD Carry",
    "Aurelion Sol": "Mid",
    "Azir": "Mid",
    "Bard": "Support",
    "Bel'Veth": "Jungler",
    "Blitzcrank": "Support",
    "Brand": "Support",
    "Braum": "Support",
    "Briar": "Jungler",
    "Caitlyn": "AD Carry",
    "Camille": "Top",
    "Cassiopeia": "Mid",
    "Cho'Gath": "Top",
    "Corki": "Mid",
    "Darius": "Top",
    "Diana": "Jungler",
    "Draven": "AD Carry",
    "Dr. Mundo": "Top",
    "Ekko": "Jungler",
    "Elise": "Jungler",
    "Evelynn": "Jungler",
    "Ezreal": "AD Carry",
    "Fiddlesticks": "Jungler",
    "Fiora": "Top",
    "Fizz": "Mid",
    "Galio": "Mid",
    "Gangplank": "Top",
    "Garen": "Top",
    "Gnar": "Top",
    "Gragas": "Top",
    "Graves": "Jungler",
    "Gwen": "Top",
    "Hecarim": "Jungler",
    "Heimerdinger": "Top",
    "Hwei": "Mid",
    "Illaoi": "Top",
    "Irelia": "Top",
    "Ivern": "Jungler",
    "Janna": "Support",
    "Jarvan IV": "Jungler",
    "Jax": "Top",
    "Jayce": "Top",
    "Jhin": "AD Carry",
    "Jinx": "AD Carry",
    "Kai'Sa": "AD Carry",
    "Kalista": "AD Carry",
    "Karma": "Support",
    "Karthus": "Jungler",
    "Kassadin": "Mid",
    "Katarina": "Mid",
    "Kayle": "Top",
    "Kayn": "Jungler",
    "Kennen": "Top",
    "Kha'Zix": "Jungler",
    "Kindred": "Jungler",
    "Kled": "Top",
    "Kog'Maw": "AD Carry",
    "K'Sante": "Top",
    "LeBlanc": "Mid",
    "Lee Sin": "Jungler",
    "Leona": "Support",
    "Lillia": "Jungler",
    "Lissandra": "Mid",
    "Lucian": "AD Carry",
    "Lulu": "Support",
    "Lux": "Support",
    "Malphite": "Top",
    "Malzahar": "Mid",
    "Maokai": "Support",
    "Master Yi": "Jungler",
    "Milio": "Support",
    "Miss Fortune": "AD Carry",
    "Wukong": "Jungler",
    "Mordekaiser": "Top",
    "Morgana": "Support",
    "Naafiri": "Mid",
    "Nami": "Support",
    "Nasus": "Top",
    "Nautilus": "Support",
    "Neeko": "Support",
    "Nidalee": "Jungler",
    "Nilah": "AD Carry",
    "Nocturne": "Jungler",
    "Nunu & Willump": "Jungler",
    "Olaf": "Top",
    "Orianna": "Mid",
    "Ornn": "Top",
    "Pantheon": "Support",
    "Poppy": "Jungler",
    "Pyke": "Support",
    "Qiyana": "Mid",
    "Quinn": "Top",
    "Rakan": "Support",
    "Rammus": "Jungler",
    "Rek'Sai": "Jungler",
    "Rell": "Support",
    "Renata Glasc": "Support",
    "Renekton": "Top",
    "Rengar": "Jungler",
    "Riven": "Top",
    "Rumble": "Top",
    "Ryze": "Mid",
    "Samira": "AD Carry",
    "Sejuani": "Jungler",
    "Senna": "Support",
    "Seraphine": "Support",
    "Sett": "Top",
    "Shaco": "Jungler",
    "Shen": "Top",
    "Shyvana": "Jungler",
    "Singed": "Top",
    "Sion": "Top",
    "Sivir": "AD Carry",
    "Skarner": "Jungler",
    "Smolder": "AD Carry",
    "Sona": "Support",
    "Soraka": "Support",
    "Swain": "Support",
    "Sylas": "Mid",
    "Syndra": "Mid",
    "Tahm Kench": "Top",
    "Taliyah": "Mid",
    "Talon": "Mid",
    "Taric": "Support",
    "Teemo": "Top",
    "Thresh": "Support",
    "Tristana": "AD Carry",
    "Trundle": "Top",
    "Tryndamere": "Top",
    "Twisted Fate": "Mid",
    "Twitch": "AD Carry",
    "Udyr": "Jungler",
    "Urgot": "Top",
    "Varus": "AD Carry",
    "Vayne": "AD Carry",
    "Veigar": "Mid",
    "Vel'Koz": "Support",
    "Vex": "Mid",
    "Vi": "Jungler",
    "Viego": "Jungler",
    "Viktor": "Mid",
    "Vladimir": "Mid",
    "Volibear": "Jungler",
    "Warwick": "Jungler",
    "Xayah": "AD Carry",
    "Xerath": "Support",
    "Xin Zhao": "Jungler",
    "Yasuo": "Mid",
    "Yone": "Mid",
    "Yorick": "Top",
    "Yuumi": "Support",
    "Zac": "Jungler",
    "Zed": "Mid",
    "Zeri": "AD Carry",
    "Ziggs": "AD Carry",
    "Zilean": "Support",
    "Zoe": "Mid",
    "Zyra": "Support"
}